import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';

export default function FaqSection() {
  const faqs = [
    {
      question: 'How does DirectSell.AI generate personalized messages?',
      answer: 'DirectSell.AI uses advanced AI models trained on successful sales and marketing communications. You provide information about your target audience and value proposition, and our AI generates tailored messages that speak directly to your prospects\' needs and pain points.'
    },
    {
      question: 'What channels can I use these messages for?',
      answer: 'The messages generated by DirectSell.AI work across all outreach channels including cold emails, LinkedIn messages, Twitter DMs, sales calls scripts, and more. You can specify the channel when generating messages to optimize for that platform\'s best practices and character limits.'
    },
    {
      question: 'Do I need sales or marketing experience to use DirectSell.AI?',
      answer: 'Not at all! DirectSell.AI is designed for everyone—from first-time founders to experienced sales professionals. The AI handles the complexity of crafting compelling messages, so you can focus on building relationships with your prospects.'
    },
    {
      question: 'How is this different from generic AI writing tools?',
      answer: 'Unlike general-purpose AI tools, DirectSell.AI is specifically trained and optimized for customer outreach and sales messaging. It understands conversion psychology, follows proven sales frameworks, and generates messages designed to get responses and book meetings—not just sound good.'
    },
    {
      question: 'Can I customize the AI-generated messages?',
      answer: 'Absolutely! Every message generated by DirectSell.AI is fully editable. Use our suggestions as a starting point and add your personal touch, specific details, or adjust the tone to match your brand voice. The AI learns from your preferences over time.'
    },
    {
      question: 'How quickly can I start reaching customers?',
      answer: 'You can generate your first personalized outreach messages in minutes. Simply describe your target audience and value proposition, and DirectSell.AI will create ready-to-use messages. Most users are actively reaching out to prospects within their first session.'
    }
  ];

  return (
    <section id="faq" className="py-16 md:py-24">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12 md:mb-16">
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Everything you need to know about using DirectSell.AI for your outreach
          </p>
        </div>

        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="space-y-4">
            {faqs.map((faq, index) => (
              <AccordionItem
                key={index}
                value={`item-${index}`}
                className="border border-border rounded-lg px-6 bg-card"
              >
                <AccordionTrigger className="text-left text-lg font-semibold hover:no-underline py-5">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-base text-muted-foreground pb-5">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
}
